name: Update from upstream
on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch: {}
jobs:
  update:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          ./update-from-upstream.sh
          changes=$(git status --short .)
          if [ -n "$changes" ]; then
            git add .
            export REV=$(nix-shell -p jq --run "cat nix/asterix-libs.json | jq -r '.rev'")
            git commit -m "Periodic sync with asterix-libs #$REV"
            git push
          fi
